spring.application.name=Ai_ChatBot
server.port=${PORT:8080}

# Gemini AI
gemini.api-key=${GEMINI_API_KEY}
gemini.model.default=gemini-2.5-flash
gemini.model.stream=gemini-2.5-flash

#PostgreSQL
#Direct
#spring.datasource.url=jdbc:postgresql://db.wjeqzbrakctsrqixzauy.supabase.co:5432/postgres?sslmode=require&tcpKeepAlive=true
#spring.datasource.username=postgres

# PostgreSQL - Supabase Pooler (Transaction mode)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require&pgbouncer=true
spring.datasource.username=postgres.wjeqzbrakctsrqixzauy

spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.initializationFailTimeout=0

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable prepared statements for PgBouncer compatibility
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000